name: learn-github-actions
on: [push]
jobs:
  my-first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: running hello world
        run: |
          echo "hello world"
          echo "Using my first job"
      
